name: Build
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run lint
    # Optional: if your workflow modifies files and needs to push them back,
    # uncomment the following step. It uses the automatically provided
    # GITHUB_TOKEN so the action can push to the repository.
    # - name: Commit and push changes
    #   run: |
    #     git config user.name "github-actions[bot]"
    #     git config user.email "github-actions[bot]@users.noreply.github.com"
    #     git add -A
    #     git commit -m "chore: workflow changes" || echo "No changes to commit"
    #     git push origin HEAD:main
